dist: xenial
services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.4"
language: python
python:
  - 3.6
env:
  - DJANGO_SETTINGS_MODULE="decide.settings" MOZ_HEADLESS=1
notifications:
  email: false
install:
        - pip install -r requirements.txt
        - pip install codacy-coverage
        - pip install flake8
before_script:
        - psql -U postgres -c "create user decide password 'decide'"
        - psql -U postgres -c "create database test_decide owner decide"
        - psql -U postgres -c "ALTER USER decide CREATEDB"
script:
        - cd decide
        - cp travis_local_settings.py local_settings.py
        - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
        - coverage xml
        - python-codacy-coverage -r coverage.xml
        - flake8 --select E501,E265,E225 . --exit-zero --exclude .git,__pycache__,docs/source/conf.py,old,build,dist,./mixnet/migrations/,./base/migrations/,./store/migrations/,./census/migrations/,./voting/migrations/
deploy:
  provider: heroku
  app: decide-dialga-auth
  strategy: git
  api_key:
    secure: oGaNF5r/lwYHicW+xTnBY7990iEpXPXVIAxPla+d2zA7UT5rrTY+2+WJlaqkMkMDSXWkiCoNW3AcwbhhcgPhZzckAqU13vZ7SWVrItKF56O3Lq0b/OQMjaFXv8rHPmnQOP5jLdrBFDql/U/+q3viCnFheE6SIt682gJ6XrOstaDAciu5XuK/P5a/toVaRbsPgeqRWxmNB/vVeF0J4sGkT/qni4TLmrB0GdLG4BsQobEwSgya6KzqGDxpp0MxrIgR/sZJdo3W8+992PbUsrYHnpJcokab1uxlaRO8n3q3v839cgkHYFiwA8VXYVyzl2oVI3hsEsisYVS/tVBo0GzNBPdvRT1T5s30l2xA4j2YDuvl/w2ZZb4XNXuvwESzD+gL2QSqkb1oxZGQKo8gEqpf1hTzOeiJtEnktCkCpkuKenYIQgfEZC3UKELOOw2KmruauLgwPABAh3bqdHiEL9X+CF1OHgCtr/dXnELiPHM2ISTPWPjtf/LTFxK6fnhvij/ZSplfX8BDahkRM9S6Z2nPS1hSLWk3jh3kxZXgXfMmTeoltp6MUaLfex/TpPt6hbW+mR99GfDbbnBZTLtTneiRsPdIokorfnt556eR95668FAGB+DePgzVYnI+KwjuNyJnWxWc9ECNeEZWNQoBSX0o//+goxRldqyTppnM0F/7SCA=
